#!/bin/bash

#https://bbs.nextthing.co/t/making-python-script-startup-project-in-chip-run-the-script-automatically-when-chip-start/7400/4

#chip@chip:~$ cat /etc/rc.local 
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.
#chgrp -R gpio /sys/class/gpio
#chmod -R g+rw /sys/class/gpio

#start my user app as a daemon
#su - chip -c '(cd /home/chip/sprinkler && ./sprink.py >/tmp/sprink.log 2>&1 ) &'
#exit 0