#!/bin/bash

install_dependencies() {
    sudo apt-get update
    sudo apt-get install git build-essential python-dev python-pip flex bison -y
}

install_dtc() {
    # Assuming we're in the Unit directory
    cd ..
    git clone https://github.com/atenart/dtc
    cd dtc
    make
    sudo make install PREFIX=/usr
}

install_chip_io() {
    cd ..
    git clone git://github.com/xtacocorex/CHIP_IO.git
    cd CHIP_IO

    sudo python setup.py install
    cd ..
    sudo rm -rf CHIP_IO  
}

install_pyrebase() {
    sudo pip install pyrebase
}

main() {
    install_dependencies
    install_dtc
    install_chip_io
    install_pyrebase
}

main